#!/bin/bash
apt-get update -y
apt-get install nano -y
apt-get install zip -y
apt-get install apache2 php5 php5-cli php5-mysql libapache2-mod-php5 php5-curl curl mysql-server-5.5  mysql-client-5.5 phpmyadmin
cd /etc/apache2
rm ports.conf
wget https://raw.githubusercontent.com/QualityNet/painel/master/ports.conf
/etc/init.d/apache2 restart
cd
useradd -m -d /home/apache -s /bin/bash apache
passwd apache
mkdir /home/apache/.sudopass
nano /home/apache/.sudopass/sudopass.secret
apt-get update -y  
apt-get install squid3 -y
cd /etc/squid3
wget https://raw.githubusercontent.com/QualityNet/painel/master/squid3.zip
unzip squid3.zip
rm squid3.zip
cd
/etc/init.d/squid3 restart
service ssh restart
service squid3 restart
service ssh restart
service squid3 restart
/etc/init.d/apache2 restart
cd /var
wget https://raw.githubusercontent.com/QualityNet/painel/master/matriz.sh
cd
apt-get update -y
cd /var/www/html
rm index.html
wget https://raw.githubusercontent.com/QualityNet/painel/master/PainelServer.zip
unzip PainelServer.zip
rm PainelServer.zip
clear
echo -e "\033[1;31mPAINEL SSH INSTALADO COM SUCESSO AGORA IMPORTE O ARQUIVO PAINEL SQL NO PHPMYADMIN.\033[0m"
